# 105
# file = open("Numbers.txt.", "w")
# file.write("1,2,3,4,5")
# file.close()
#  106
# file = open("Names.txt.", "w")
# file.write("Vadim\n")
# file.write("Vova\n")
# file.write("Vitalik\n")
# file.write("Vladislav\n")
# file.write("Vermishel\n")
# file.close()
# 107
# file = open("Names.txt", "r")
# print(file.read())
# file.close()
# 108
# file = open("Names.txt.", "a")
# a = input("Введите имя: ")
# file.write(f"\n{a}")
# file = open("Names.txt", "r")
# print(file.read())
# file.close()
# 109
# print("1) Create a new file \n2) Display the file \n3) Add a new item to the file ")
# a = int(input("\nMake a selection 1, 2 or 3:"))
# if a == 1:
#     file = open("Subject.txt", "w")
#     b = input("Введите название предмета: \n")
#     file.write(f"\n{b}")
# elif a == 2:
#     file = open("Subject.txt", "r")
#     print(file.read())
# elif a == 3:
#     file = open("Subject.txt", "a")
#     c = input("Введите название нового предмета: \n")
#     file.write(f"\n{c}")
#     file = open("Subject.txt", "r")
#     print(file.read())
#     file.close()
# else:
#     print("Error")
# 110
file = open("Names.txt", "r")
print(file.read())
file.close()
a = input("Введите Имя: \n")
if a == "Vadim":
    file = open("Names2.txt", "w")
    file.write("Vova\n")
    file.write("Vitalik\n")
    file.write("Vladislav\n")
    file.write("Vermishel\n")
    file.write("EvgenykolyaDmitriy\n")
    file.write("Vasiliy\n")
    file.close()
elif a == "Vova":
    file = open("Names2.txt", "w")
    file.write("Vadim\n")
    file.write("Vitalik\n")
    file.write("Vladislav\n")
    file.write("Vermishel\n")
    file.write("EvgenykolyaDmitriy\n")
    file.write("Vasiliy\n")
    file.close()
elif a == "Vitalik":
    file = open("Names2.txt", "w")
    file.write("Vadim\n")
    file.write("Vova\n")
    file.write("Vladislav\n")
    file.write("Vermishel\n")
    file.write("EvgenykolyaDmitriy\n")
    file.write("Vasiliy\n")
    file.close()
elif a == "Vladislav":
    file = open("Names2.txt", "w")
    file.write("Vadim\n")
    file.write("Vova\n")
    file.write("Vitalik\n")
    file.write("Vermishel\n")
    file.write("EvgenykolyaDmitriy\n")
    file.write("Vasiliy\n")
    file.close()
elif a == "Vermishel":
    file = open("Names2.txt", "w")
    file.write("Vadim\n")
    file.write("Vova\n")
    file.write("Vitalik\n")
    file.write("Vladislav\n")
    file.write("EvgenykolyaDmitriy\n")
    file.write("Vasiliy\n")
    file.close()
elif a == "EvgenykolyaDmitriy":
    file = open("Names2.txt", "w")
    file.write("Vadim\n")
    file.write("Vova\n")
    file.write("Vitalik\n")
    file.write("Vladislav\n")
    file.write("Vermishel\n")
    file.write("Vasiliy\n")
    file.close()
elif a == "Vasiliy":
    file = open("Names2.txt", "w")
    file.write("Vadim\n")
    file.write("Vova\n")
    file.write("Vitalik\n")
    file.write("Vladislav\n")
    file.write("Vermishel\n")
    file.write("EvgenykolyaDmitriy\n")
    file.close()
else:
    print("Такого имени в списке нет(")